version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sentence-validation"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pzqlbpn27n4w"
s3_prefix = "sentence-validation"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
